exports.employees = [
    {firstName: "Shirley", middleName: "C.", lastName: "Pearson", email: "ShirleyCPearson@dayrep.com", phone: "225-803-5760", startTime: "9am" , endTime: "5pm", salary: "$95000"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "IT"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "IT"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "IT"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "IT"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "IT"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Legal"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Legal"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Legal"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Legal"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Legal"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "HR"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "HR"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "HR"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Sales"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Sales"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Sales"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Sales"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Sales"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "Sales"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "PR and Marketing"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "PR and Marketing"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "PR and Marketing"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "PR and Marketing"},
    {firstName: "John", middleName: "M.", lastName: "Smith", email: "johnsmith@dayrep.com", phone: "390-576-2210", startTime: "9am" , endTime: "5pm", salary: "$97000", department: "PR and Marketing"},
]
